// <auto-generated />
using System;
using LibraryProjectSep2019;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryProjectSep2019.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryProjectSep2019.Book", b =>
                {
                    b.Property<string>("IsbnNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookName")
                        .IsRequired();

                    b.Property<int>("BooksCategory");

                    b.Property<DateTime>("IssuedDate");

                    b.Property<int>("IssuedUserID");

                    b.Property<decimal>("ReplacementPrice");

                    b.HasKey("IsbnNumber")
                        .HasName("PK_IsbnNumber");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryProjectSep2019.Customer", b =>
                {
                    b.Property<int>("UserIDOfCustomer")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("UserIDOfCustomer")
                        .HasName("PK_UserID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LibraryProjectSep2019.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("IsbnNumber")
                        .IsRequired();

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionType");

                    b.Property<int>("UserIDOfCustomer");

                    b.HasKey("Id")
                        .HasName("PK_TransactionID");

                    b.HasIndex("IsbnNumber");

                    b.HasIndex("UserIDOfCustomer");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("LibraryProjectSep2019.Transaction", b =>
                {
                    b.HasOne("LibraryProjectSep2019.Book", "TransactionBook")
                        .WithMany()
                        .HasForeignKey("IsbnNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryProjectSep2019.Customer", "TransactionCustomer")
                        .WithMany()
                        .HasForeignKey("UserIDOfCustomer")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
